openapi: 3.0.0
info:
  title: Ticket Show API
  description: >-
    This API specification specifies REST API on The Ticket Show app on Venues
    and Shows. Following are the schemas and endpoints to interact with the api!


    <h3> Venue Table Schema </h3> <table> <thead> <th>Column Name</th>
    <th>Column Type</th> <th>Constraints</th> </thead> <tbody> <tr>
    <td>venue_id</td> <td>Integer</td> <td>Primary Key, Auto Increment</td>
    </tr> <tr> <td>name</td> <td>String</td> <td>Not Null</td> </tr> <tr>
    <td>place</td> <td>String</td> <td>Not Null</td> </tr> <tr>
    <td>capacity</td> <td>Integer</td> <td>Not Null</td> </tr>

    </tbody> </table>

    <h3> Show Table Schema </h3> <table> <thead> <th>Column Name</th> <th>Column
    Type</th> <th>Constraints</th> </thead> <tbody> <tr> <td>show_id</td>
    <td>Integer</td> <td>Primary Key, Auto Increment</td> </tr> <tr>
    <td>title</td> <td>String</td> <td>Not Null</td> </tr> <tr>
    <td>description</td> <td>String</td> <td>-</td> </tr> <tr>
    <td>start_time</td> <td>String</td> <td>Not Null</td> </tr> <tr>
    <td>end_time</td> <td>String</td> <td>Not Null</td> </tr> <tr>
    <td>ticket_price</td> <td>Integer</td> <td>Not Null</td> </tr> <tr>
    <td>venue_id</td> <td>Integer</td> <td>Not Null, Foreign
    Key(Venue.venue_id)</td> </tr> </tbody> </table>


    <h3> Error Codes </h3> <table> <thead> <th>Resource</th> <th>Error Code</th>
    <th>Message</th> </thead> <tbody> <tr> <td>Venue</td> <td>NAME</td>
    <td>Venue Name is required</td> </tr> <tr> <td>Venue</td> <td>PLACE</td>
    <td>Place/City is required</td> </tr> <tr> <td>Venue</td> <td>CAPACITY</td>
    <td>CAPACITY is required</td> </tr> <tr> <td>Show</td> <td>SHOW001</td>
    <td>Show title is required</td> </tr> <tr> <td>Show</td> <td>SHOW002</td>
    <td>Show start Time is required</td> </tr>

    <tr> <td>Show</td> <td>SHOW003</td> <td>Show end Time is required</td> </tr>
    <tr> <td>Show</td> <td>SHOW004</td> <td>Ticket Price is required</td> </tr>
    <tr> <td>Show</td> <td>SHOW005</td> <td>Venue ID for show is required</td>

    </tr> </tbody> </table>
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/
  - url: http://127.0.0.1:5000/
paths:
  /api/v1/venue/{venue_id}:
    description: >-
      End point to read, update and delete a Venue resource with venue_id =
      venueId.
    get:
      description: Operation to Read venue resource.
      parameters:
        - in: path
          name: venue_id
          required: true
          schema:
            type: integer
            example: 201
      responses:
        '404':
          description: Venue not found
        '500':
          description: Internal Server Error
    put:
      description: Operation to update the venue resource.
      parameters:
        - in: path
          name: venue_id
          required: true
          schema:
            type: integer
            example: 201
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: PVR
                place:
                  type: string
                  example: KOP
                capacity:
                  type: integer
                  example: 250
      responses:
        '200':
          description: Successfuly updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  venue_id:
                    type: integer
                    example: 201
                  name:
                    type: string
                    example: PVR
                  place:
                    type: string
                    example: KOLHAPUR
                  capacity:
                    type: integer
                    example: 300
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
        '404':
          description: Venue not found
        '500':
          description: Internal Server Error
    delete:
      description: Operation to delete the venue resource
      parameters:
        - in: path
          name: venue_id
          required: true
          schema:
            type: integer
            example: 201
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description: Venue not found
        '500':
          description: Intenal Server Error
  /api/v1/venue:
    description: End point to create new Venue resource
    post:
      description: Operation to create the venue resource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: PVR
                place:
                  type: string
                  example: KOLHAPUR
                capacity:
                  type: integer
                  example: 250
      responses:
        '201':
          description: Successfully Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  venue_id:
                    type: integer
                    example: 2
                  name:
                    type: string
                    example: PVR
                  place:
                    type: string
                    example: MUMBAI
                  capacity:
                    type: integer
                    example: 260
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
        '409':
          description: venue_id already exist
        '500':
          description: Internal Server Error
  /api/v1/show/{show_id}:
    description: Url to read, update and delete the show resource.
    get:
      description: Operation to read show resource
      parameters:
        - in: path
          name: show_id
          required: true
          schema:
            type: integer
            example: 201
      responses:
        '200':
          description: Request Successful
          content:
            application/json:
              schema:
                title: Show object
                type: object
                properties:
                  title:
                    type: string
                    example: The Avengers
                  description:
                    type: string
                    example: show_description
                  start_time:
                    type: string
                    example: yyyy-mm-dd hh:mm
                  end_time:
                    type: string
                    example: yyyy-mm-dd hh:mm
                  ticket_price:
                    type: integer
                    example: 262
                  venue_id:
                    type: integer
                    example: 2
        '404':
          description: Show not found
        '500':
          description: Internal server error
    put:
      description: Operation to update the show resource
      parameters:
        - in: path
          name: show_id
          required: true
          schema:
            type: integer
            example: 101
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: The Avengers
                description:
                  type: string
                  example: show_description
                start_time:
                  type: string
                  example: yyyy-mm-dd hh:mm
                end_time:
                  type: string
                  example: yyyy-mm-dd hh:mm
                ticket_price:
                  type: integer
                  example: 262
                venue_id:
                  type: integer
                  example: 2
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: The Avengers
                  description:
                    type: string
                    example: show_description
                  start_time:
                    type: string
                    example: yyyy-mm-dd hh:mm
                  end_time:
                    type: string
                    example: yyyy-mm-dd hh:mm
                  ticket_price:
                    type: integer
                    example: 262
                  venue_id:
                    type: integer
                    example: 2
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
        '404':
          description: Student not found
        '500':
          description: Internal Server Error
    delete:
      description: Operation to delete the Show resource
      parameters:
        - in: path
          name: show_id
          required: true
          schema:
            type: integer
            example: 101
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description: Show not found
        '500':
          description: Internal Server Error
  /api/v1/show:
    description: Url to create Show resource
    post:
      description: Operation to create new Show resource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: The Avengers
                description:
                  type: string
                  example: show_description
                start_time:
                  type: string
                  example: yyyy-mm-dd hh:mm
                end_time:
                  type: string
                  example: yyyy-mm-dd hh:mm
                ticket_price:
                  type: integer
                  example: 262
                venue_id:
                  type: integer
                  example: 2
      responses:
        '201':
          description: Successfully Created
          content:
            application/json:
              schema:
                title: Show object
                type: object
                properties:
                  title:
                    type: string
                    example: The avengers
                  description:
                    type: string
                    example: show_description
                  start_time:
                    type: string
                    example: yyyy-mm-dd hh:mm
                  end_time:
                    type: string
                    example: yyyy-mm-dd hh:mm
                  ticket_price:
                    type: integer
                    example: 262
                  venue_id:
                    type: integer
                    example: 2
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
        '409':
          description: show already exist
        '500':
          description: Internal Server Error
